refactor(images): swap spotify icons
Rigtch/rigtch-music-www pull request #94
Opened 2023-09-25 12:52 UTC by Iqro-dev

closes #93

2023-09-25 12:54 UTC, Iqro-dev commented
spotify-logo.png import works perfectly fine, however when i try to import the icons provided by spotify e.g. spotify-icon-green.png it just doesn't show in the browser

2023-09-28 17:04 UTC, Mnigos requested changes
Use external link icon instead of spotify icon.

2023-09-29 12:43 UTC, Mnigos requested changes
change color of icon before and after hover and change transition duration

2023-09-29 13:04 UTC, Mnigos approved these changes

2023-09-29 15:01 UTC, merged